#!/usr/bin/env bash

# Transfers a file from our client to a server

# Check if enough arguments are provided
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Transfer file using scp with strict host key checking disabled
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
