#!/usr/bin/env bash
# This script creates an RSA key pair with the given parameters

# Set the filename for the private key
private_key="school"
ssh-keygen -t rsa -b 4096 -N "betty" -f ~/.ssh/"$private_key"
